### ISSUE TITLE
[PERFORMANCE] Use FX2D

### ISSUE THREAD

**Issue by CodeLikeCrazE** [carykh/VirusGame#32]
I tested the sim with FX2D and it is considerably faster. That's all.

**Comment by sleepybraincells** [comment]
When I tried it, it gave this error message:

java.lang.RuntimeException: Please use Sketch → Import Library to add JavaFX to your sketch.
	at processing.core.PApplet.makeGraphics(PApplet.java:1938)
	at processing.core.PApplet.createPrimaryGraphics(PApplet.java:1975)
	at processing.core.PApplet.initSurface(PApplet.java:10160)
	at processing.core.PApplet.runSketch(PApplet.java:10121)
	at processing.core.PApplet.main(PApplet.java:9845)
RuntimeException: Please use Sketch → Import Library to add JavaFX to your sketch.


>

**Comment by CodeLikeCrazE** [comment]
Use Sketch -> Import Library then. :^)
